---
title: "Results_SimpleGrid"
author: "Jennifer Blanc"
date: "2024-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(tidyverse)
library(latex2exp)
library(ggpubr)
```

## Bias Plots

```{r, message=FALSE, warning=FALSE}
# Read in results 
df <- fread("../plots/SimpleGrid/A/EqualSS/q_LMM.txt")
df <- df [,3:ncol(df)]
df <- df %>% filter(type != 35)

# Average Bias and false positive rate 
dfPlot <- df %>% group_by(gwas_size, test_size, h2, num_causal, env, L, type, pheno, test) %>% summarize(count = n(), avg_q = mean(`nc-q`),lowerci_mean = avg_q - (1.96 * (sd(`nc-q`)  /  sqrt(n()))), upperci_mean = avg_q + (1.96 * (sd(`nc-q`)  /  sqrt(n()))), fp_strat = sum(`nc-p` < 0.05)/ n(), lowerci_fp = fp_strat - 1.96 * sqrt((fp_strat * (1-fp_strat))/ n()), upperci_fp = fp_strat + 1.96 * sqrt((fp_strat * (1-fp_strat))/ n()), q_std = avg_q / sd(`nc-q`))

# Order the types
dfPlot$type <- factor(dfPlot$type, levels = c("NoCorrection","10", "FGr" ,"LMMNoCorrection"))

# Read in longitude results 
dfLong <- fread("../plots/SimpleGrid/A/EqualSS/q_long.txt")
dfLong <- dfLong[,3:ncol(dfLong)]
tmp <- fread("../plots/SimpleGrid/A/EqualSS/q_LMM_long.txt") 
tmp <- tmp[,3:ncol(tmp)]
tmp <- tmp %>% filter(pheno == "DIAG" & test == "LAT")
dfLong <- rbind(dfLong, tmp)


# Average Bias and false positive rate 
dfPlot_Long <- dfLong %>% group_by(gwas_size, test_size, h2, num_causal, env, L, type, pheno, test) %>% summarize(count = n(), avg_q = mean(`nc-q`),lowerci_mean = avg_q - (1.96 * (sd(`nc-q`)  /  sqrt(n()))), upperci_mean = avg_q + (1.96 * (sd(`nc-q`)  /  sqrt(n()))), fp_strat = sum(`nc-p` < 0.05)/ n(), lowerci_fp = fp_strat - 1.96 * sqrt((fp_strat * (1-fp_strat))/ n()), upperci_fp = fp_strat + 1.96 * sqrt((fp_strat * (1-fp_strat))/ n()), q_std = avg_q / sd(`nc-q`))
dfPlot_Long$test <- "Longitude"
dfPlot_Long$type <- factor(dfPlot_Long$type, levels = c("NoCorrection","10", "FGr","LMMNoCorrection" ))

# Substitute names of tests 
dfPlot$test <- gsub("LAT", "Latitude", dfPlot$test)
dfPlot$test <- gsub("PS", "Single Deme", dfPlot$test)
```


```{r}
# Function to make bar plots with bias 
plot_bias <- function(df, pheno_type, test_type, env_type) {
  
  pl <- df %>% filter(pheno == pheno_type  & env == env_type & type != "ID") %>% filter(test %in% test_type ) %>% ggplot(aes(x = type, y = avg_q, fill = type)) + geom_col()+ geom_point(fill = "black", size = 3) + geom_hline(yintercept = 0, color = "red") + geom_errorbar(aes(ymin = lowerci_mean, ymax = upperci_mean), width = 0.2) +
  theme_classic(base_size = 12) + theme(panel.border = element_rect(colour = "black", fill=NA, size=1), axis.text.x = element_text(size = 8, color = "black",  angle = 35, hjust=1), legend.position = "none", legend.text.align = 0) + 
  scale_fill_manual(values = c("goldenrod2", "red4" , "navy", "turquoise4")) + scale_x_discrete(labels = unname(TeX(c("Uncorrected", "10 PCs", "$\\hat{F}_{Gr}$", "LMM")))) + xlab("") + ylab("Bias") + facet_wrap(~test)
  
  return(pl)
}

# Plot bias 
plLL <- plot_bias(dfPlot,"LAT", "Latitude", 0.2)
plLL
plDL <- plot_bias(rbind(dfPlot, dfPlot_Long), "DIAG", c("Latitude", "Longitude"), 0.2)
plDL
plPS <- plot_bias(dfPlot,"PS", "Single Deme", 0.2)
plPS

```

## PRS Plots

```{r}

plot_PRS <- function(dfNC, dfFGr, dfPCs, dfLMMs, ll, up) {
  
  # No Correction
  plNC <- ggplot(data =dfNC, aes(x = LONG, y = LAT, fill = avg_PRS)) + geom_tile() +  theme_classic(base_size = 12) +  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) + scale_fill_gradient2(low = "brown4", high = "royalblue4", name = "PGS", limits = c(ll, up)) + xlab("Longitude") + ylab("Latitude") + scale_y_continuous(breaks=seq(0,6,1)) + scale_x_continuous(breaks=seq(0,6,1)) + theme(axis.title = element_blank())
  
  # FGr included
  plFGr <- ggplot(data =dfFGr, aes(x = LONG, y = LAT, fill = avg_PRS)) + geom_tile() +  theme_classic(base_size = 12) +  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) + scale_fill_gradient2(low = "brown4", high = "royalblue4", name = "PGS", limits = c(ll, up)) + xlab("Longitude") + ylab("Latitude") + scale_y_continuous(breaks=seq(0,6,1)) + scale_x_continuous(breaks=seq(0,6,1)) + theme(axis.title = element_blank())
  
  # 10 PCs included
  plPCs <- ggplot(data =dfPCs, aes(x = LONG, y = LAT, fill = avg_PRS)) + geom_tile() +  theme_classic(base_size = 12) +  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) + scale_fill_gradient2(low = "brown4", high = "royalblue4", name = "PGS", limits = c(ll, up)) + xlab("Longitude") + ylab("Latitude") + scale_y_continuous(breaks=seq(0,6,1)) + scale_x_continuous(breaks=seq(0,6,1)) + theme(axis.title = element_blank())
  
  # LMM
  plLMM <- ggplot(data =dfPCs, aes(x = LONG, y = LAT, fill = avg_PRS)) + geom_tile() +  theme_classic(base_size = 12) +  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) + scale_fill_gradient2(low = "brown4", high = "royalblue4", name = "PGS", limits = c(ll, up)) + xlab("Longitude") + ylab("Latitude") + scale_y_continuous(breaks=seq(0,6,1)) + scale_x_continuous(breaks=seq(0,6,1)) + theme(axis.title = element_blank())
  
  # Combine plots
  pl <- ggpubr::ggarrange(plNC, plFGr, plPCs, plLMM, common.legend = T, legend="right", nrow = 1)
  
}

# Lat/Lat
dfNC <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/LAT/LAT/prs-NoCorrection_L-20000.txt")
dfFGr <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/LAT/LAT/prs-FGr_L-20000.txt")
dfPCs <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/LAT/LAT/prs-10_L-20000.txt")
dfLMM <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/LAT/LAT/prs-LMMNoCorrection_L-20000.txt")
prsLL <- plot_PRS(dfNC, dfFGr, dfPCs, dfLMM, -.6, .6)
prsLL


# Diag/Lat
dfNC <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/DIAG/LAT/prs-NoCorrection_L-20000.txt")
dfFGr <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/DIAG/LAT/prs-FGr_L-20000.txt")
dfPCs <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/DIAG/LAT/prs-10_L-20000.txt")
dfLMM <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/DIAG/LAT/prs-LMMNoCorrection_L-20000.txt")
prsDL <- plot_PRS(dfNC, dfFGr, dfPCs,dfLMM, -.28, .28)
prsDL

# PS/PS
dfNC <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/PS/PS/prs-NoCorrection_L-20000.txt")
dfFGr <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/PS/PS/prs-FGr_L-20000.txt")
dfPCs <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/PS/PS/prs-10_L-20000.txt")
dfLMM <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/PS/PS/prs-LMMNoCorrection_L-20000.txt")
prsPS <- plot_PRS(dfNC, dfFGr, dfPCs, dfLMM, -.12, .12)
prsPS
```

## Phenotype Plots 

```{r}
# Function to plot phenotype grid
plot_pheno <- function(df) {
  
  pl <- ggplot(df, aes(x = LONG, y = LAT, fill = avg_PRS)) + geom_tile() + theme_classic(base_size = 12) +  theme(panel.border = element_rect(colour = "black", fill=NA, size=1), legend.position = "none") + scale_fill_gradient2(low = "palegoldenrod", high = "purple4") + xlab("Longitude") + ylab("Latitude") + scale_y_continuous(breaks=seq(0,6,1)) + scale_x_continuous(breaks=seq(0,6,1)) + theme(axis.title = element_blank())
  
  return(pl)
}

# Lat
df <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/LAT/phenos_L-20000.txt")
phenoLat <- plot_pheno(df)
phenoLat

# Diag
df <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/DIAG/phenos_L-20000.txt")
phenoDiag <- plot_pheno(df)
phenoDiag

# PS 
df <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/PS/phenos_L-20000.txt")
phenoPS <- plot_pheno(df)
phenoPS
```

## Final Figure 4
```{r}
sv1 <- ggpubr::ggarrange(phenoLat, prsLL, plLL, nrow = 1, widths = c(0.11, 0.48, 0.14))
sv2 <- ggpubr::ggarrange(phenoDiag, prsDL, plDL, nrow = 1, widths = c(0.11, 0.48, 0.14))
sv3 <- ggpubr::ggarrange(phenoPS, prsPS, plPS, nrow = 1, widths = c(0.11, 0.48, 0.14))

out <- ggarrange(sv1, sv2, sv3, nrow = 4, ncol = 1)
ggsave("~/Desktop/fig4.png", out, height = 10, width = 16)
```

## Variance Explained Plots 

#### Confounder

```{r}
make_confounder_plot <- function(df, lab_title) {
  
  pl  <- ggplot(data = df, aes(x = PC, y = avg_r2)) + geom_bar(stat = "identity", fill = "purple4", aes( alpha = color)) + ylab(TeX("$R^2$")) + xlab("Cumulative PCs") + theme_classic(base_size = 14) + ylim(0,1)+ scale_alpha_manual(values = c(0.25, 1), guide="none") + geom_hline(yintercept = 1, color = "red", linetype = "longdash", size = 1.5) +theme( plot.title=element_text(hjust = 0.9,vjust=-40, face='bold', size = 12)) + ggtitle(lab_title) + geom_vline(xintercept = 35, color = "black", linetype = "longdash", size = 1)
  #+ geom_point(size = 1, aes( alpha = color)) 
  
  return(pl)
}

make_FGr_plot <- function(df, lab_title) {
  
  pl  <- ggplot(data = df, aes(x = PC, y = avg_r2)) + geom_bar(stat = "identity", fill = "navy", aes( alpha = color)) + ylab(TeX("$R^2$")) + xlab("Cumulative PCs") + theme_classic(base_size = 14) + ylim(0,1)+ scale_alpha_manual(values = c(0.25, 1), guide="none") + geom_hline(yintercept = 1, color = "red", linetype = "longdash", size = 1.5) +theme( plot.title=element_text(hjust = 0.9,vjust=-40, face='bold', size = 12)) + ggtitle(lab_title) + geom_vline(xintercept = 35, color = "black", linetype = "longdash", size = 1)
  #+ geom_point(size = 1, aes( alpha = color)) 
  
  return(pl)
}
```



```{r}
dfLat <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/LAT/confounder_varEx-L-20000.txt")[,2:6]
colnames(dfLat)[1] <- "PC"
dfLat$color <-c(rep("TRUE", 10), rep("FALSE", 1429))
dfLat <- dfLat[1:100,]


dfDiag <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/DIAG/confounder_varEx-L-20000.txt")[,2:6]
colnames(dfDiag)[1] <- "PC"
dfDiag$color <-c(rep("TRUE", 10), rep("FALSE", 1429))
dfDiag <- dfDiag[1:100,]

dfPS <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/env_0.2/PS/confounder_varEx-L-20000.txt")[,2:6]
colnames(dfPS)[1] <- "PC"
dfPS$color <-c(rep("TRUE", 10), rep("FALSE", 1429))
dfPS <- dfPS[1:100,]

cLat <- make_confounder_plot(dfLat, "Latitude")
cDiag <- make_confounder_plot(dfDiag, "Diagonal")
cPS <- make_confounder_plot(dfPS, "Single Deme")

cLat
cDiag
cPS
```


```{r}
dfLat <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/LAT/FGr_varEx-L-20000.txt")[,2:6]
colnames(dfLat)[1] <- "PC"
dfLat$color <-c(rep("TRUE", 10), rep("FALSE", 1429))
dfLat <- dfLat[1:100,]

dfPS <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/h2-0.0/c-300/PS/FGr_varEx-L-20000.txt")[,2:6]
colnames(dfPS)[1] <- "PC"
dfPS$color <-c(rep("TRUE", 10), rep("FALSE", 1429))
dfPS <- dfPS[1:100,]

fLat <- make_FGr_plot(dfLat, "Latitude")
fPS <- make_FGr_plot(dfPS, "Single Deme")
fLat
fPS
```

```{r}
pl <- ggarrange(cLat,  fLat, cDiag, fLat, cPS, fPS, ncol=2, nrow =3)
pl
ggsave("~/Desktop/R2.png", pl, height = 8)
```

## Figure 5 

```{r}
df <- fread("../plots/SimpleGrid/A/EqualSS/q_PS.txt")[,3:19]
tmp <- fread("../plots/SimpleGrid/A/EqualSS/q_PS_LMM.txt")[,3:19]
df <- rbind(df,tmp)
x <- seq(2000, 20000, 2000 )

# Average Bias and false positive rate 
dfPlot <- df %>% group_by(gwas_size, test_size, h2, num_causal, env, L, type, pheno, test) %>% summarize(count = n(), avg_q = mean(`nc-q`),lowerci_mean = avg_q - (1.96 * (sd(`nc-q`)  /  sqrt(n()))), upperci_mean = avg_q + (1.96 * (sd(`nc-q`)  /  sqrt(n()))), fp_strat = sum(`nc-p` < 0.05)/ n(), lowerci_fp = fp_strat - 1.96 * sqrt((fp_strat * (1-fp_strat))/ n()), upperci_fp = fp_strat + 1.96 * sqrt((fp_strat * (1-fp_strat))/ n()), q_std = avg_q / sd(`nc-q`)) %>% filter(pheno == "PS" & test == "PS" & L %in% x) 

# Order type
dfPlot$type <- factor(dfPlot$type, levels = c("NoCorrection","LMMNoCorrection","10", "35", "FGr"))
dfPlot$TEST <- "Single Deme"

# Plot 
pl <- ggplot(data = dfPlot, aes(x = L, y = avg_q, color = type)) + geom_point(size = 2.5, position=position_dodge(width=1800)) + geom_hline(yintercept = 0, color = "red") + geom_errorbar(aes(ymin = lowerci_mean, ymax = upperci_mean),  width = 2000, position=position_dodge(width=1800)) +  
  theme_bw(base_size = 14) + theme(legend.position = "right", panel.border = element_rect(colour = "black", fill=NA, size=1), legend.text = element_text(size = 12), panel.grid.minor = element_line(linetype = 'dashed'), strip.background =element_rect(fill="white")) + ylab("") +
  scale_color_manual(values = c("goldenrod2","turquoise4", "red4", "darkorange3", "navy"), labels = c("No Correction","LMM", "10 PCs", "35 PCs", TeX("$\\hat{F}_{Gr}$")), name = "") + facet_wrap(~TEST) 
pl

ggsave("~/Desktop/PS_Bias.png", pl, width = 7, height = 4)
```


```{r}
df <- fread("../plots/SimpleGrid/A/EqualSS/q_LAT.txt")[,3:19]
tmp <- fread("../plots/SimpleGrid/A/EqualSS/q_LAT_LMM.txt")[,3:19]
df <- rbind(df,tmp)


# Average Bias and false positive rate 
dfPlot <- df %>% group_by(gwas_size, test_size, h2, num_causal, env, L, type, pheno, test) %>% summarize(count = n(), avg_q = mean(`nc-q`),lowerci_mean = avg_q - (1.96 * (sd(`nc-q`)  /  sqrt(n()))), upperci_mean = avg_q + (1.96 * (sd(`nc-q`)  /  sqrt(n()))), fp_strat = sum(`nc-p` < 0.05)/ n(), lowerci_fp = fp_strat - 1.96 * sqrt((fp_strat * (1-fp_strat))/ n()), upperci_fp = fp_strat + 1.96 * sqrt((fp_strat * (1-fp_strat))/ n()), q_std = avg_q / sd(`nc-q`)) %>% filter(L %in% x)

# Order type
dfPlot$type <- factor(dfPlot$type, levels = c("NoCorrection","LMMNoCorrection","10", "35", "FGr"))
dfPlot$TEST <- "Latitude"

# Plot 
pl <- ggplot(data = dfPlot, aes(x = L, y = avg_q, color = type)) + geom_point(size = 2.5, position=position_dodge(width=1800)) + geom_hline(yintercept = 0, color = "red") + geom_errorbar(aes(ymin = lowerci_mean, ymax = upperci_mean),  width = 2000, position=position_dodge(width=1800)) +  
  theme_bw(base_size = 14) + theme(legend.position = "right", panel.border = element_rect(colour = "black", fill=NA, size=1), legend.text = element_text(size = 12), panel.grid.minor = element_line(linetype = 'dashed'), strip.background =element_rect(fill="white")) + ylab("Bias") +
  scale_color_manual(values = c("goldenrod2","turquoise4", "red4", "darkorange3", "navy"), labels = c("No Correction", "LMM","10 PCs", "35 PCs", TeX("$\\hat{F}_{Gr}$")), name = "") + facet_wrap(~TEST)
pl

ggsave("~/Desktop/LAT_Bias.png", pl, width = 7, height = 4)
```


```{r}

df <- fread("../plots/SimpleGrid/A/EqualSS/q_PS_LMM.txt")[,3:19]

# Average Bias and false positive rate 
dfPlot <- df %>% group_by(gwas_size, test_size, h2, num_causal, env, L, type, pheno, test) %>% summarize(count = n(), avg_q = mean(`nc-q`),lowerci_mean = avg_q - (1.96 * (sd(`nc-q`)  /  sqrt(n()))), upperci_mean = avg_q + (1.96 * (sd(`nc-q`)  /  sqrt(n()))), fp_strat = sum(`nc-p` < 0.05)/ n(), lowerci_fp = fp_strat - 1.96 * sqrt((fp_strat * (1-fp_strat))/ n()), upperci_fp = fp_strat + 1.96 * sqrt((fp_strat * (1-fp_strat))/ n()), q_std = avg_q / sd(`nc-q`)) %>% filter(L %in% x)

# Order type
dfPlot$type <- factor(dfPlot$type, levels = c("NoCorrection","10", "35", "FGr"))
dfPlot$TEST <- "Latitude"

# Plot 
pl <- ggplot(data = dfPlot, aes(x = L, y = avg_q, color = type)) + geom_point(size = 2.5, position=position_dodge(width=1800)) + geom_hline(yintercept = 0, color = "red") + geom_errorbar(aes(ymin = lowerci_mean, ymax = upperci_mean),  width = 2000, position=position_dodge(width=1800)) +  
  theme_bw(base_size = 14) + theme(legend.position = "right", panel.border = element_rect(colour = "black", fill=NA, size=1), legend.text = element_text(size = 12), panel.grid.minor = element_line(linetype = 'dashed'), strip.background =element_rect(fill="white")) + ylab("Bias") +
  scale_color_manual(values = c("goldenrod2", "red4", "darkorange3", "navy"), labels = c("No Correction","10 PCs", "35 PCs", TeX("$\\hat{F}_{Gr}$")), name = "") + facet_wrap(~TEST) 
pl

#ggsave("~/Desktop/LAT_Bias.png", pl, width = 7, height = 4)
```


## Supplemental Figure 

```{r}
df <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/LAT/FGr_L-20000.txt")
df$test <- "Latitude"
df2 <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/PS/FGr_L-20000.txt")
df2$test <- "Single Deme"
df <- rbind(df, df2)

  
pl <- ggplot(data = df, aes(x = LONG, y = LAT, fill = avg_FGr)) + geom_tile() +  theme_classic(base_size = 16) + facet_wrap(~test) +  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) + scale_fill_gradient2(low = "goldenrod2", high = "red4", name = TeX("$\\hat{F}_{Gr}$")) + xlab("Longitude") + ylab("Latitude") + scale_y_continuous(breaks=seq(0,6,1)) + scale_x_continuous(breaks=seq(0,6,1))  + ylab("Latitude") + xlab("Longitude")


ggsave("~/Desktop/FGr_grids.png", pl, height = 5, width = 8)
```








