---
title: "SimpleGrid_Error"
author: "Jennifer Blanc"
date: "2024-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
```

```{r}
x <- seq(4000, 20000, 2000)
df <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/LAT/Error-L-6000.txt")
df$L <- 2000
df$num <- c(NA, seq(1, 100))

for (i in x) {
  
  tmp <- fread(paste0("../plots/SimpleGrid/A/gp-1440/tp-1440/LAT/Error-L-", i, ".txt"))
  tmp$L <- i
  tmp$num <- c(NA, seq(1, 100))
  df <- rbind(df,tmp)
  
  
}

dfFGr <- df %>% filter(Type == "FGr")
dfPC <- df %>% filter(Type != "FGr")
```

```{r}
x <- seq(4000, 20000, 2000)
df2 <- fread("../plots/SimpleGrid/A/gp-1440/tp-1440/PS/Error-L-6000.txt")
df2$L <- 2000
df2$num <- c(NA, seq(1, 100))

for (i in x) {
  
  tmp <- fread(paste0("../plots/SimpleGrid/A/gp-1440/tp-1440/PS/Error-L-", i, ".txt"))
  tmp$L <- i
  tmp$num <- c(NA, seq(1, 100))
  df2 <- rbind(df2,tmp)
  
  
}

dfFGr2 <- df2 %>% filter(Type == "FGr")
dfFGr$Type <-"Latitude"
dfFGr2$Type  <- "Single Deme"
dfFGr <- rbind(dfFGr, dfFGr2)
```


```{r}
p1 <- ggplot(dfFGr, aes(x = Type, y = Error, color = L)) + geom_point(size=3) + ylim(0,1.05) +
  theme_bw(base_size = 14) + theme(panel.border = element_rect(colour = "black", fill=NA, size=1), axis.text.x = element_text(size = 8, color = "black"), legend.position = "none",  panel.grid.minor = element_line(linetype = 'dashed')) + xlab(TeX("$\\hat{F}_{Gr}$")) + geom_hline(yintercept = 0, color = "red") + ylab("Error") + scale_color_gradient(low = "navy", high = "cadetblue1")

p2 <- ggplot(dfPC, aes(x = num, y = Error, color = L)) + geom_point() + ylim(0, 1.05) + geom_point(size=3) + 
  theme_bw(base_size = 14) + theme(panel.border = element_rect(colour = "black", fill=NA, size=1), axis.text.x = element_text(size = 8, color = "black"), legend.position = "none", panel.grid.minor = element_line(linetype = 'dashed')) + xlab("Principal Components") + geom_hline(yintercept = 0, color = "red") + geom_vline(xintercept = 35, color = "black", linewidth=1.2, linetype = "longdash") + ylab("Error Lower Bound") + scale_color_continuous(low = "red4",high = "red1")

pl <- egg::ggarrange(p1, p2, nrow=1, widths = c(0.25, 0.75))
pl
#ggsave("~/Desktop/error_grids.png", pl, width = 10, height = 5)
```

```{r}
p1 <- ggplot(dfFGr, aes(x = Type, y = Error, color = L)) + geom_point(size=3) + ylim(0,1.05) +
  theme_bw(base_size = 14) + theme(panel.border = element_rect(colour = "black", fill=NA, size=1), axis.text.x = element_text(size = 8, color = "black"),  panel.grid.minor = element_line(linetype = 'dashed')) + xlab(TeX("$\\hat{F}_{Gr}$")) + geom_hline(yintercept = 0, color = "red") + ylab("Error") + scale_color_gradient(low = "navy", high = "cadetblue1", breaks = c(2000, 8000, 14000, 20000))
p1

p2 <- ggplot(dfPC, aes(x = num, y = Error, color = L)) + geom_point() + ylim(0, 1.05) + geom_point(size=3) + 
  theme_bw(base_size = 14) + theme(panel.border = element_rect(colour = "black", fill=NA, size=1), axis.text.x = element_text(size = 8, color = "black"), panel.grid.minor = element_line(linetype = 'dashed')) + xlab("Principal Components") + geom_hline(yintercept = 0, color = "red") + geom_vline(xintercept = 35, color = "black", linewidth=1.2, linetype = "longdash") + ylab("Error Lower Bound") + scale_color_continuous(low = "red4",high = "red1",breaks = c(2000, 8000, 14000, 20000))
p2
#ggsave("~/Desktop/p1_legend.png", p1, width = 10, height = 5)
```



## Real data results 

```{r}
dfError <- fread("../../stratification-data_analysis/plots/pga_paper/error.txt")
dfError <- dfError[3:10, ]

ggplot(data = dfError, aes(x = L, y = error, color = contrast)) + geom_point(size = 3) + scale_x_log10() + ylab(TeX("$\\hat{F}_{Gr}$\\\ Error")) + 
  theme_bw(base_size = 14) + theme(panel.border = element_rect(colour = "black", fill=NA, size=1), panel.grid.minor = element_line(linetype = 'dashed'), legend.position = "bottom") + scale_color_manual(values = c("purple1", "seagreen1"), name = "Test Vector")
```

```{r}
dfQ <- fread("../../stratification-data_analysis/plots/pga_paper/q.txt")
dfQ <- dfQ %>% distinct()
for (i in 1:nrow(dfQ)) {
  dfQ$contrast[i] <- str_split(dfQ$contrast[i], ".all")[[1]][1]
}
dfQ$L <- as.character(dfQ$L)

dfFGr <- dfQ %>% filter(covar == "FGr-LOCO")
dfNo <- dfQ %>% filter(covar == "no-FGr")
dfNo <- dfNo[1:2,]
dfNo$L <- "Uncorrected"

df <- rbind(dfFGr, dfNo)
df$L <- factor(df$L, levels = c( "Uncorrected","1000","10000","1e+05","1e+06"))

ggplot(data = df, aes( x = phenotype, y = L, fill = q)) + geom_tile() + facet_grid(vars(contrast)) + scale_fill_gradient2(low = "brown4", high = "royalblue4", name = TeX("$\\hat{q}$"))

#+ geom_text(aes(label=sig), color="black", size=7, fontface="bold") + theme_bw(base_size = 14) + xlab("") + ylab("Test panel size") + ggtitle("Education Attainment: Test = North")
```

```{r}
ggplot(df, aes(x = L, y = q)) + facet_wrap(~contrast) + geom_point()
```

